version: '3.7'

services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_DATABASE=docker_db
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
#  docker-app:
#    image: project:latest
#    ports:
#      - 8080:8080
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/docker_db
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=
#    networks:
#      - backend
volumes:
  mariadb_data:
    driver: local
networks:
  backend:
